<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Application accepted</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="stylesheet" href="style.css" media="all"/>
</head>
<body>
	<div>
		<h3>PROFESSIONAL SERVICES AGREEMENT</h3>
		<p>Between:</p>
		<p>{{$practice->practice_name}}, {{$practice->practice_city}}, {{$practice->practice_province}}, {{$practice->practice_postal_code}}, {{$practice->practice_address1}} (the “employer”)</p>
		<p>and</p>
		<p>{{$user->name}}, {{$user->city}}, {{$user->province}}, {{$user->postal_code}}, {{$user->user_address1}} (the "Service Provider")</p>
		<p>for the Term of </p>
		<p>{{date("m/d/Y", strtotime($job->job_start))}} to {{date("m/d/Y", strtotime($job->job_end))}}</p>
		<p>under the follow terms of remuneration</p>
		@if($job->percentage!='')
			<p>{{$job->percentage}}% of Revenue Generated by the Service Provider </p>
		@else
			<p>${{$job->day_rate}} per Day</p>
		@endif
		<p>Provided by LocumOD (the "Service Facilitator")</p>
		<p>Where the employer agrees to appoint the Service Provider as and optometric service provider under the following terms and conditions provided by the Service Facilitator. </p>

		<h3>SERVICE PROVIDERS SERVICES AND RESPONSIBILITIES:</h3>
		<ul type="1">
			<li>The Service Provider will be responsible for providing, without limitation, medical care relating to vision therapy and related services that are required for the successful treatment of patients as dictated by the Provincial requirements of the practice of Optometry in the employers Canadian Province. </li>
			<li>Providing such skills and advice in order to prescribe and recommend ophthalmic products related to but limited to eyeglasses, contact lenses, sunglasses, accessories and treatments. </li>
			<li>Obtaining and maintaining professional liability insurance as stipulated by the Provincial College of Optometry.</li>
			<li>Be in good standing with and abide by all standards set by the local Provincial College of Optometry. Maintaining all appropriate licences, permits and registrations necessary to practice as a Dr. of Optometry within the employer’s geographic region.</li>
		</ul>

		<h3>EMPLOYERS</h3>
		<ul type="1">
			<li>Provide the necessary facilities and staff to enable the Service Provider to provide Optometric Services at the Practice location. </li>
			<li>Provide evidence of all necessary insurance and safety certificates as required in the local Province.</li>
			<li>Provide a clean, safe working environment for the service provider.</li>
			<li>Provide instruction of safety procedures for the building.</li>
		</ul>

		<h3>CONFIDENTIAL INFORMATION:</h3>
		<ul type="1">
			<li>The Service Provider will have unrestricted access to Patient information. All information will be considered the property of the practice and should not be removed from the location at the end of the Service Providers term. Patient information should not be misused, disclosed or shared in any way in accordance with any applicable Privacy Legislation in effect.</li>
			<li>Any Patients seen by the Service Provider will be considered the property of the Employers Practice after the term. The Service Provider agrees that there will be no solicitation of Patients to another Practice and that guardianship of the Patient data will reside solely with the Employers Practice. </li>
		</ul>

		<h3>TERM:</h3>
		<ul type="1">
			<li>The “Term” is described as the period which the Service Provider agrees to attend the Employers Practice.</li>
			<li>Any extension to the Term should be processed through LocumOD and result in the issue of a revised version of this contract. </li>
		</ul>

		<h3>RENUMERATION:</h3>
		<h3>PERCENTAGE RATE</h3>
		<ul type="1">
			<li>The Service Provider has agreed to be paid a % of the revenue they generate from sales associated with their patient bookings. This includes but is not limited to Exam Fees, Product Sales and other associated services that are charged by the Practice. </li>
			<li>Applicable Revenue shall be considered that which is associated with a patient seen by the Service Provider on the day of service. Revenue is based on the total Sale value of that day and not the Receipt value. </li>
			<li>The Employer must provide a report of the Sales generated by the Service Provider at the end of each Day of Service for the Term. </li>
			<li>The Service Provider will issue an invoice based on the the agreed percentage of the total sale value shown in the report.</li>
		</ul>

		<h3>DAY RATE</h3>
		<ul type="1">
			<li>The Service Provider has agreed to be paid a flat Day Rate based solely on the number of days the Service Provider provides service to the employer. </li>
			<li>The Service Provider will issue an invoice based on the Term of service at the end of the Term. </li>
		</ul>

		<h3>DELIVERY:</h3>
		<h3>THE SERVICE PROVIDER</h3>
		<ul type="1">
			<li>Agrees to make all reasonable efforts to arrive on time and ready to deliver their services at the agreed time and date.</li>
			<li>Ensures any change to circumstances that may impact the prompt provision of services should be communicated immediately and directly to the employer.</li>
		</ul>

		<h3>THE EMPLOYER</h3>
		<ul type="1">
			<li>Agrees to make all reasonable efforts to ensure their Practice and Staff are ready to receive the Service Provider on the agreed time and date. </li>
			<li>Ensures any change in circumstances that may impact the ability to receive the Service Providers services should be communicated immediately and directly to the Service Provider. </li>
		</ul>

		<h3>EXCEPTIONS:</h3>
		<h3>LOCUMOD</h3>
		<ul>
			<li>Acts as a booking facilitator between the Service Provider and the Employer, it does not accept responsibility for ensuring that delivery is maintained. It does however offer a communication and feedback platform that can be used to ensure you have the ability to stay in contact to adhere to the Delivery Terms above.</li>
			<li>Does not take responsibility for the actions of Service Providers or Employers in any way once they have left the <a href="http://162.243.87.85">www.locumOD.com</a> site environment.</li>
			<li>Is at liberty to restrict or remove comments and feedback related to performance that it feels are against the Terms and Conditions agreed to during the sign up process.</li>
			<li>Does not take any responsibility for the payment of Service Providers or issue of invoices to Employers. This is the sole responsibility of the Service Provider and Employer. </li>
		</ul>

		<h3>THE FOLLOWING PARTIES HAVE EXECUTED THIS AGREEMENT AS OF THE DATE ABOVE.</h3>
		<p>The Service Provider</p>
		<p>Signature:</p>.........................................
		<p>Date:</p>.........................................
		<p>{{$user->name}}</p>
		<p>The Employer</p>
		<p>Signature:</p>.........................................
		<p>Date:</p>.........................................
		<p>{{$practice->practice_name}}</p>
	</div>
</body>
</html>